export struct Course {
    name: string,
    checkpoints: [int]
}

export enum MistakeType {missed, shuffle}
export enum ResultType {success, fail}

export struct Mistake {
    type: MistakeType,
    checkpoint: int,
}
export struct Grade {
    mistakes: [Mistake],
    result: string,
    course: string,
    time: string,
}


export enum GuiState {
    settings,running,editor
}

export global Utils {
    pure callback find(array:[string], value: string) -> int;
}

// export struct BackendState {
//     si_connected: bool,
//     other_thing: string,
// }