import { AboutSlint, VerticalBox, Button, ComboBox, ListView } from "std-widgets.slint";
import { HorizontalDivider } from "material-1.0/ui/components/divider.slint";
import {Grade, Mistake, ResultType, MistakeType} from "datatypes.slint";

export component RunningWindow inherits Rectangle {

    in property <Grade> grade;
    callback request-return-to-settings;

    HorizontalLayout {
        VerticalBox {
            HorizontalLayout{
                spacing: 10px;
                Text {
                    text: "Course";
                    vertical-alignment: TextVerticalAlignment.center;
                }
                ComboBox {
                    model: ["Dog", "Bird", "Other"];
                }
            }

            HorizontalDivider { }

            ListView {
                for item[index] in grade.mistakes: Text {
                    text: "Missed Checkpoint \{item.checkpoint}!";
                }
            }
        }

        VerticalBox {
            horizontal-stretch: 1;
            preferred-width: 100%;
            response_image:= Image {
                image-fit: ImageFit.contain;
            }
            VerticalBox {
                alignment: LayoutAlignment.start;
                Text {
                    font-size: 40px;
                    horizontal-alignment: TextHorizontalAlignment.center;
                    text: "Time: \{grade.time}";
                }
                response_text := Text {
                    font-size: 40px;
                    horizontal-alignment: TextHorizontalAlignment.center;
                }
            }

            states [
                success when grade.result == "success": {
                    response_image.source: @image-url("resources/TryAgainFace.png");
                    response_text.text: "Good job!";
                }
                fail when grade.result != "success": {
                    response_text.text: "Try Again!";
                    response_image.source: @image-url("resources/YayFace.png");
                }
            ]
        }
    }

    VerticalBox {
        alignment: LayoutAlignment.end;
        HorizontalLayout {
            alignment: LayoutAlignment.end;
            Button {
                text: "Return to setup";
                clicked => { request-return-to-settings(); }
            }
        }
    }
}