import { AboutSlint, VerticalBox,HorizontalBox, StandardButton, ComboBox, Button } from "std-widgets.slint";

export component SettingsWindow inherits VerticalLayout {
    in property <bool> si_connected;
    in property <bool> feature_flag_course_sets;

    // [TODO]: when this property changes, we re-trigger a port connection. lets add some logic in here to not do that.
    in property <[string]> available_ports;

    callback request-connect-si(port:string);

    Text {
        font-size: 17pt;
        horizontal-alignment: TextHorizontalAlignment.center;
        vertical-alignment: TextVerticalAlignment.center;
        text: "Connect reader and select port to get started";

        //                 text: root.connected ? "You're connected. Press START to begin" : "Connect reader and select port to get started"
        //                 color: root.text_color
        //                 font.pointSize: 17
        //                 font.bold: true
        //                 font.family: "Arial"
    }

    footer := Rectangle {
        background: #313131;
        height: 40px;
        HorizontalBox {
            footer_left := HorizontalLayout {
                alignment: LayoutAlignment.start;
                spacing: 25px;

                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: "Port:";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    port_dropdown := ComboBox {
                        model: available_ports;
                        changed current-value => { request-connect-si(self.current-value); }
                    }
                }
                HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: "Scoring Mode:";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    score_mode_dropdown := ComboBox {
                        model: ["Animal-O", "Score-O", "Classic-O"];
                    }
                }

                if feature_flag_course_sets: HorizontalLayout {
                    spacing: 10px;
                    Text {
                        text: "Course Set:";
                        vertical-alignment: TextVerticalAlignment.center;
                    }
                    course_set_dropdown := ComboBox {
                        model: ["builtins"];
                    }
                }
            }


            footer_right := HorizontalLayout {
                alignment: LayoutAlignment.end;

                Button {
                    enabled: root.si_connected;
                    text: "Start";
                }
            }
        }
    }
}
