// Light theme
export global Theme {
    // brand colors
    out property <color> navgames_orange: #ff683a;
    out property <color> navgames_blue: #0090f8;

    // app chrome
    out property <color> window_bg: #fffbf9;
    out property <color> chrome_bg: #ffffff;
    out property <color> chrome_text: #444444;
    out property <color> chrome_accent: root.navgames_orange;
    out property <color> chrome_shadow: #00000030;

    // widget colors
    out property <color> divider: #d9d0cb;
    out property <color> outline: #85736c;
    out property <color> disabled_bg: #0000001f;
    out property <color> disabled_text: #00000061;

    // feedback colors
    out property <color> success_green: #9ae99d;
    out property <color> info_blue: #cbd9ff;
    out property <color> bad_red: #ff9090;
}
